export enum Stages {
  INICIO, //1
  CARDAPIO_SELECIONADO, //2
  CATEGORIA_SELECIONADA, //3
  PRODUTO_SELECIONADO, //4
  EXIBIR_ADICIONAIS, //5
  CONFIRMAR_ADICIONAIS, //6
  CONFIRMAR_PRODUTO, //7
  ADICIONAR_CONFIRMAR_PRODUTOS, //8,
  ENDERECO, //9
  PAGAMENTO, //10
  CONFIRMAR_CANCELAR_PEDIDO, //11
  FINALIZAR, //12
}
